export const C2E_DIGITAL_DOCUMENT_TYPE = 'sdons:DigitalDocument';
export const C2E_RESOURCE_COLLECTION_ID = 'c2ens:c2eResources';
export const C2E_CONTENT_TYPE_COLLECTION_ID = 'c2ens:c2eContentTypes';
export const C2E_SOURCE_CODE_ID = 'c2ens:c2eSourceCode';
export const C2E_COLLECTION_TYPE = 'sdons:Collection';
export const C2E_DATASET_TYPE = 'sdons:Dataset';
export const C2E_CONTENT_STRING_DATA_TYPE = 'xsd:string'; // https://www.w3.org/TR/xmlschema-2/#string
export const C2E_CONTENT_BOOLEAN_DATA_TYPE = 'xsd:boolean';
export const C2E_CONTENT_DECIMAL_DATA_TYPE = 'xsd:decimal';
export const C2E_CONTENT_FLOAT_DATA_TYPE = 'xsd:float';
export const C2E_CONTENT_DOUBLE_DATA_TYPE = 'xsd:double';
export const C2E_CONTENT_DATETIME_DATA_TYPE = 'xsd:dateTime';
export const C2E_CONTENT_DATE_DATA_TYPE = 'xsd:date';
export const C2E_CONTENT_TIME_DATA_TYPE = 'xsd:time';